### ISSUE TITLE
Incorrect pinouts (Red LED,Reader TXD)

### ISSUE THREAD

**Issue by zymurgic** [dawidekziaja/acnode-doorbot#1]
Raising an issue here so we document the issues on the board, even if we do a software workaround instead of mod wire. Probably mod wire, since UART ports can't be remapped.

- Red LED (RJ45 BLUE pin 4) should connect to PM_0 on the Launchpad, not PK5
- Reader TXD (RJ45 WHITE/GREEN pin 3)/Launchpad RXD PP0 not PB4

**Comment by dawidziaja** [comment]
Fixed in 227654a
